In [1]:
import plotly.express as px
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import datetime
#pandas.read_excel('cat.xlsx', engine='openpyxl')

In [4]:
df1 = pd.read_csv("Keller GroundWorks CRM Data 1.txt",usecols=['o_OPPORTUNITYID',"ID","o_OpportunityStatus","o_ProjectManager","o.OPENEDDATE","o_CLOSEDDATE","o_HC_STATE","o_HC_PRIMARYTECHNIQUE","o_HC_PRELIMPRICE","o_HC_LATESTAMT","o_HC_FUNDINGID","o_HC_STRUCTURE","o_HC_MARKETID","sq_HC_ESTGMPCT","sq_HC_AMOUNT","sq_HC_ESTCOST","sq_HC_ESTGM","o_HC_TECHNIQUENAME","o_TechniqueGroup","br_SEGMENT","gp_HasMoreTechniques","sq_QUOTATIONEXPIRYDATE","it_HC_INFLUENCERROLE"], sep = "\t", encoding = "ISO-8859-1", low_memory=False)

In [5]:
df2 = pd.read_csv("Keller GroundWorks CRM Data 2.txt",usecols=['o_OPPORTUNITYID',"ID","o_OpportunityStatus","o_ProjectManager","o.OPENEDDATE","o_CLOSEDDATE","o_HC_STATE","o_HC_PRIMARYTECHNIQUE","o_HC_PRELIMPRICE","o_HC_LATESTAMT","o_HC_FUNDINGID","o_HC_STRUCTURE","o_HC_MARKETID","sq_HC_ESTGMPCT","sq_HC_AMOUNT","sq_HC_ESTCOST","sq_HC_ESTGM","o_HC_TECHNIQUENAME","o_TechniqueGroup","br_SEGMENT","gp_HasMoreTechniques","sq_QUOTATIONEXPIRYDATE","it_HC_INFLUENCERROLE"], sep = "\t", encoding = "ISO-8859-1", low_memory=False)

In [2]:
df3 = pd.read_csv("Keller GroundWorks CRM Data 1.txt", sep = "\t", encoding = "ISO-8859-1", low_memory=False)

In [ ]:
#df2 = pd.read_csv("Keller GroundWorks CRM Data 2.txt",usecols=['o_OPPORTUNITYID',"ID","o_OpportunityStatus","o_ProjectManager","o.OPENEDDATE","o_CLOSEDDATE","o_HC_STATE","o_HC_PRIMARYTECHNIQUE","o_HC_PRELIMPRICE","o_HC_LATESTAMT","o_HC_FUNDINGID","o_HC_STRUCTURE","o_HC_MARKETID","sq_HC_ESTGMPCT","sq_HC_AMOUNT","sq_HC_ESTCOST","sq_HC_ESTGM","o_HC_TECHNIQUENAME","o_TechniqueGroup","br_SEGMENT","gp_HasMoreTechniques","sq_QUOTATIONEXPIRYDATE","it_HC_INFLUENCERROLE"], sep = "\t", encoding = "ISO-8859-1", low_memory=False)

In [6]:
df_1=df1
df_2=df2

In [1184]:
df1=df_1
df2=df_2

In [3]:
import dtale
e = dtale.show(df3)
e.open_browser()

In [7]:
df1 = df1[(df1["o_OpportunityStatus"]=="Won") | (df1["o_OpportunityStatus"]=="Lost")]
df2 = df2[(df2["o_OpportunityStatus"]=="Won") | (df2["o_OpportunityStatus"]=="Lost")]

In [8]:
#df1 = df1[(df1["o_OpportunityStatus"]=="Won")]
#df2 = df2[(df2["o_OpportunityStatus"]=="Won")]

In [8]:
df = pd.concat((df1,df2))

In [9]:
duplicates = df.duplicated(['o_OPPORTUNITYID'], keep='first')
df = df[~duplicates]
if isinstance(df, (pd.DatetimeIndex, pd.MultiIndex)):
	df = df.to_frame(index=False)

# remove any pre-existing indices for ease of use in the D-Tale code, but this is not required
df = df.reset_index().drop('index', axis=1, errors='ignore')
df.columns = [str(c) for c in df.columns]  # update columns to strings in case they are numbers

In [10]:
df_12=df["sq_HC_ESTGMPCT"].astype("str")
df_123=df_12.apply(lambda x: x.replace(',', '.'))
df_1234=df_123.astype("float")
df["sq_HC_ESTGMPCT"]=df_1234

In [11]:
df_12=df["sq_HC_AMOUNT"].astype("str")
df_123=df_12.apply(lambda x: x.replace(',', '.'))
df_1234=df_123.astype("float")
df["sq_HC_AMOUNT"]=df_1234

In [12]:
df_12=df["sq_HC_ESTCOST"].astype("str")
df_123=df_12.apply(lambda x: x.replace(',', '.'))
df_1234=df_123.astype("float")
df["sq_HC_ESTCOST"]=df_1234

In [13]:
df_12=df["sq_HC_ESTGM"].astype("str")
df_123=df_12.apply(lambda x: x.replace(',', '.'))
df_1234=df_123.astype("float")
df["sq_HC_ESTGM"]=df_1234

In [14]:
df["sq_HC_AMOUNT"].dropna(how='any',inplace=True)
df["sq_HC_ESTCOST"].dropna(how='any',inplace=True)
df["sq_HC_ESTGM"].dropna(how='any',inplace=True)
df["sq_HC_ESTGMPCT"].dropna(how='any',inplace=True)

In [15]:
df_12=df["o_HC_PRELIMPRICE"].astype("str")
df_123=df_12.apply(lambda x: x.replace(',', '.'))
df_1234=df_123.astype("float")
df["o_HC_PRELIMPRICE"]=df_1234

In [16]:
df_12=df["o_HC_LATESTAMT"].astype("str")
df_123=df_12.apply(lambda x: x.replace(',', '.'))
df_1234=df_123.astype("float")
df["o_HC_LATESTAMT"]=df_1234

In [17]:
df_12=df["o_HC_PRIMARYTECHNIQUE"].astype("str")
df_123=df_12.apply(lambda x: x[1:4])
#df_1234=df_123.astype("int")
df["o_HC_PRIMARYTECHNIQUE"]=df_123
df=df[df["o_HC_PRIMARYTECHNIQUE"]!="an"]
df=df[df["o_HC_PRIMARYTECHNIQUE"]!="eve"]

In [18]:
df["sq_HC_AMOUNT"].fillna(method="ffill",inplace=True)
df["sq_HC_ESTCOST"].fillna(method="ffill",inplace=True)
df["sq_HC_ESTGM"].fillna(method="ffill",inplace=True)
df["sq_HC_ESTGMPCT"].fillna(method="ffill",inplace=True)

In [19]:
df=df[df['sq_HC_ESTGM']>=0]

In [20]:
df["o_HC_FUNDINGID"][df["o_HC_FUNDINGID"]=="PRIvate"]="Private"
df["o_HC_FUNDINGID"][df["o_HC_FUNDINGID"]=="fed/State"]="Fed/State"
df["o_HC_FUNDINGID"][df["o_HC_FUNDINGID"]=="local"]="Local"
df["o_HC_FUNDINGID"][df["o_HC_FUNDINGID"]=="private"]="Private"
df["o_HC_FUNDINGID"][df["o_HC_FUNDINGID"]=="state"]="State"
df=df[df["o_HC_FUNDINGID"]!="Canopy"]

<ipython-input-20-375ef5ca348e>:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<ipython-input-20-375ef5ca348e>:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<ipython-input-20-375ef5ca348e>:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<ipython-input-20-375ef5ca348e>:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-d

In [1101]:
df["o_HC_FUNDINGID"].dropna(inplace=True)

In [1102]:
df["o_HC_FUNDINGID"].head(10)

0       Private
1       Private
2     Fed/State
3     Fed/State
4     Fed/State
5       Federal
8       Private
9       Private
10      Private
11      Private
Name: o_HC_FUNDINGID, dtype: object

In [1060]:
df=df['br_SEGMENT'].dropna()

KeyError: 'br_SEGMENT'

In [1147]:
#df=df[['o_OpportunityStatus',"o_HC_FUNDINGID","br_SEGMENT"]]

In [23]:
import dtale
d = dtale.show(df)
d.open_browser()

In [1125]:
df["o_HC_FUNDINGID"].unique()

array(['Private', 'Fed/State', 'Federal', 'State', 'Local'], dtype=object)

In [973]:
df['o_HC_FUNDINGID']

0          Private
1          Private
2        Fed/State
3        Fed/State
4        Fed/State
           ...    
32313      Private
32314      Private
32315      Private
32316      Private
32317        Local
Name: o_HC_FUNDINGID, Length: 27779, dtype: object

In [1126]:
from sklearn.preprocessing import LabelEncoder

ord_enc = LabelEncoder()
df['o_HC_FUNDINGID'] = ord_enc.fit_transform(df[['o_HC_FUNDINGID']])
df['o_HC_FUNDINGID'].head(10)

0    3
1    3
2    0
3    0
4    0
5    1
6    5
7    5
8    3
9    3
Name: o_HC_FUNDINGID, dtype: int32

In [1127]:
df['br_SEGMENT']

0          Contractor/CM
1          Contractor/CM
2          Contractor/CM
3          Contractor/CM
4          Contractor/CM
              ...       
32313      Contractor/CM
32314      Contractor/CM
32315    Owner/Developer
32316      Contractor/CM
32317          Education
Name: br_SEGMENT, Length: 31619, dtype: object

In [1128]:
ord_enc = LabelEncoder()
df['br_SEGMENT'] = ord_enc.fit_transform(df[['br_SEGMENT']])
df['br_SEGMENT'].head(10)

0     7
1     7
2     7
3     7
4     7
5    10
6    16
7    16
8     7
9     7
Name: br_SEGMENT, dtype: int32

In [1129]:
df["o_HC_FUNDINGID"].unique()

array([3, 0, 1, 5, 4, 2], dtype=int64)

In [1130]:
df['br_SEGMENT'].unique()

array([ 7, 10, 16,  3, 14,  6,  5,  8, 13, 12,  1,  4,  9, 15,  2,  0, 11],
      dtype=int64)

# A

In [21]:
from sklearn.preprocessing import LabelEncoder
is_nan = df['o_OpportunityStatus'].isnull()
df['o_OpportunityStatus']=pd.Series(LabelEncoder().fit_transform(df['o_OpportunityStatus']), index=df.index).where(~is_nan, 0)

2021-06-18 12:49:56,302 - INFO     - NumExpr defaulting to 4 threads.


In [22]:
from sklearn.preprocessing import LabelEncoder
is_nan = df['o_HC_STATE'].isnull()
df['o_HC_STATE']=pd.Series(LabelEncoder().fit_transform(df['o_HC_STATE']), index=df.index).where(~is_nan, 0)

In [23]:
from sklearn.preprocessing import LabelEncoder
is_nan = df['o_HC_FUNDINGID'].isnull()
df['o_HC_FUNDINGID']=pd.Series(LabelEncoder().fit_transform(df['o_HC_FUNDINGID']), index=df.index).where(~is_nan, 0)

In [24]:
from sklearn.preprocessing import LabelEncoder
is_nan = df['o_HC_MARKETID'].isnull()
df['o_HC_MARKETID']=pd.Series(LabelEncoder().fit_transform(df['o_HC_MARKETID']), index=df.index).where(~is_nan, 0)

In [25]:
from sklearn.preprocessing import LabelEncoder
is_nan = df['o_TechniqueGroup'].isnull()
df['o_TechniqueGroup']=pd.Series(LabelEncoder().fit_transform(df['o_TechniqueGroup']), index=df.index).where(~is_nan, 0)

In [26]:
from sklearn.preprocessing import LabelEncoder
is_nan = df['br_SEGMENT'].isnull()
df['br_SEGMENT']=pd.Series(LabelEncoder().fit_transform(df['br_SEGMENT']), index=df.index).where(~is_nan, 0)

In [27]:
from sklearn.preprocessing import LabelEncoder
is_nan = df["o_ProjectManager"].isnull()
df["o_ProjectManager"]=pd.Series(LabelEncoder().fit_transform(df["o_ProjectManager"]), index=df.index).where(~is_nan, 0)

In [28]:
from sklearn.preprocessing import LabelEncoder
is_nan = df["o_HC_STRUCTURE"].isnull()
df["o_HC_STRUCTURE"]=pd.Series(LabelEncoder().fit_transform(df["o_HC_STRUCTURE"]), index=df.index).where(~is_nan, 0)

In [29]:
from sklearn.preprocessing import LabelEncoder
is_nan = df["o_HC_TECHNIQUENAME"].isnull()
df["o_HC_TECHNIQUENAME"]=pd.Series(LabelEncoder().fit_transform(df["o_HC_TECHNIQUENAME"]), index=df.index).where(~is_nan, 0)

In [30]:
from sklearn.preprocessing import LabelEncoder
is_nan = df["gp_HasMoreTechniques"].isnull()
df["gp_HasMoreTechniques"]=pd.Series(LabelEncoder().fit_transform(df["gp_HasMoreTechniques"]), index=df.index).where(~is_nan, 0)

In [31]:
from sklearn.preprocessing import LabelEncoder
is_nan = df["it_HC_INFLUENCERROLE"].isnull()
df["it_HC_INFLUENCERROLE"]=pd.Series(LabelEncoder().fit_transform(df["it_HC_INFLUENCERROLE"]), index=df.index).where(~is_nan, 0)

In [32]:
df_12=df["o.OPENEDDATE"]
df_123=df_12.apply(lambda x: x.split(' ')[0])
df["o.OPENEDDATE"]=df_123

In [33]:
df_12=df["o_CLOSEDDATE"]
df_123=df_12.apply(lambda x: x.split(' ')[0])
df["o_CLOSEDDATE"]=df_123

In [767]:
#df_12=df["sq_QUOTATIONEXPIRYDATE"]
#df_123=df_12.apply(lambda x: x.split(' ')[0])
#df["sq_QUOTATIONEXPIRYDATE"]=df_123

In [768]:
df["o_CLOSEDDATE"]

0        02/04/2020
1        02/04/2020
2        01/01/1900
3        10/03/2020
4        08/03/2021
            ...    
32313    26/12/2019
32314    01/01/1900
32315    01/01/1900
32316    01/01/1900
32317    01/01/1900
Name: o_CLOSEDDATE, Length: 31862, dtype: object

In [769]:
def my_date(x):
    if x == "01/01/1900":
        x ="20/05/2021"
    return x

In [770]:
def my_date1(x,y):
    for i in x.index:
        if x.iloc[i] == "01/01/1900":
            x.iloc[i] = y.iloc[i]
        return x

In [771]:
#df["o_CLOSEDDATE"]=my_date1(df["o_CLOSEDDATE"],df["sq_QUOTATIONEXPIRYDATE"])

In [772]:
df["o_CLOSEDDATE"]=df["o_CLOSEDDATE"].apply(lambda x: my_date(x))

In [773]:
df["o.OPENEDDATE"]=pd.to_datetime(df['o.OPENEDDATE'])
df["o_CLOSEDDATE"]=pd.to_datetime(df["o_CLOSEDDATE"])

In [774]:
df["how_long"]=df["o_CLOSEDDATE"] - df["o.OPENEDDATE"]

In [32]:
df["sq_HC_AMOUNT"].fillna(method="ffill",inplace=True)
df["sq_HC_ESTCOST"].fillna(method="ffill",inplace=True)
df["sq_HC_ESTGM"].fillna(method="ffill",inplace=True)
df["sq_HC_ESTGMPCT"].fillna(method="ffill",inplace=True)

In [776]:
df["how_long"]=df["how_long"].dt.days

In [34]:
df=df[df['sq_HC_ESTGM']>=0]

In [778]:
#df["o_HC_FUNDINGID"][df["o_HC_FUNDINGID"]=="PRIvate"]="Private"
#df["o_HC_FUNDINGID"][df["o_HC_FUNDINGID"]=="fed/State"]="Fed/State"
#df["o_HC_FUNDINGID"][df["o_HC_FUNDINGID"]=="local"]="Local"
#df["o_HC_FUNDINGID"][df["o_HC_FUNDINGID"]=="private"]="Private"
#df["o_HC_FUNDINGID"][df["o_HC_FUNDINGID"]=="state"]="State"
#df[df["o_HC_FUNDINGID"]!="Canopy"]

In [866]:
df["o_HC_FUNDINGID"].unique()

array([3, 0, 1, 4, 2], dtype=int64)

In [867]:
df["br_SEGMENT"].unique()

array([ 7, 10,  0,  3, 14,  6,  5,  8, 13, 12,  1,  4,  9, 15,  2, 11],
      dtype=int64)

In [781]:
#df=df[df["how_long"]>=0]

In [35]:
del df['o.OPENEDDATE']
del df['o_CLOSEDDATE']
del df['sq_QUOTATIONEXPIRYDATE']

In [36]:
del df["o_OPPORTUNITYID"]

del df["o_CLOSEDDATE"]
#del df['index']

KeyError: 'o_CLOSEDDATE'

In [784]:
#from sklearn.preprocessing import LabelEncoder
#is_nan = df['o_HC_FUNDINGID'].isnull()
#df['o_HC_FUNDINGID']=pd.Series(LabelEncoder().fit_transform(df['o_HC_FUNDINGID']), index=df.index).where(~is_nan, 0)

In [785]:
#df=df.iloc[:14999]

In [868]:
#df=df[df["o_HC_FUNDINGID"]!=0]
#df=df[df["br_SEGMENT"]!=0]

In [ ]:
del df["o_OPPORTUNITYID"]

del df['ID']

In [38]:
import dtale
d = dtale.show(df)
d.open_browser()

Executing shutdown due to inactivity...


2021-06-18 14:51:00,298 - INFO     - Executing shutdown due to inactivity...


Executing shutdown...


2021-06-18 14:51:39,328 - INFO     - Executing shutdown...
